name: three_patti_usa
publish_to: 'none'
description: 3 Patti Social premium full-screen iOS lobby and multiplayer prototype.
version: 1.5.0+16

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/avatars/
