name: three_patti_usa
publish_to: 'none'
description: 3 Patti Social premium full-screen iOS lobby and multiplayer prototype.
version: 0.5.1+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
